#!/bin/bash
set -euo pipefail
this_dir=$(cd $(dirname $0); pwd -P)

docker buildx build \
  --platform linux/amd64 \
  --iidfile $this_dir/docker-id.txt \
  --file $this_dir/Dockerfile \
  $this_dir/docker

docker_id=$(cat $this_dir/docker-id.txt)

docker run \
  --platform linux/amd64 \
  --volume $this_dir:/src/tuning-tool \
  --rm \
  -it \
  $docker_id
