[package]
name = "midi-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
num = "0.4.3"
path-absolutize = "3.1.1"
rust_decimal = "1.36.0"
