[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[workspace]
members = [
    "tuning-tool",
    "tuning-tool-lib",
    "tuning-tool-macros",
    "tuning-tool-macros-test",
]
resolver = "2"
