[package]
edition = "2021"
name = "tuning-tool-derive-tests"
version = "0.1.0"

[dependencies]
midly = "0.5.3"
tuning-tool-derive = { path = "../tuning-tool-derive" }
tuning-tool-lib = { path = "../tuning-tool-lib" }
