[package]
edition = "2021"
name = "tuning-tool-macros-test"
version = "0.0.0"

[dependencies]
tuning-tool-lib = { path = "../tuning-tool-lib" }
tuning-tool-macros = { path = "../tuning-tool-macros" }
