name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 5 * * *

jobs:
  ci:
    strategy:
      matrix:
        target:
          #- x86_64-apple-darwin
          #- x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
        include:
          #- target: x86_64-apple-darwin
          #  host_os: macos-13
          #- target: x86_64-pc-windows-msvc
          #  host_os: windows-latest
          - target: x86_64-unknown-linux-gnu
            host_os: ubuntu-latest
    runs-on: ${{ matrix.host_os }}
    steps:
      - name: Install dependencies
        if: matrix.host_os == 'ubuntu-latest'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libasound-dev
          ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012
          ls /usr/local/lib/x86_64-linux-gnu || true
          ls /lib/x86_64-linux-gnu || true
          ls /usr/lib/x86_64-linux-gnu || true
          ls /usr/lib/x86_64-linux-gnu64 || true
          ls /usr/local/lib64 || true
          ls /lib64 || true
          ls /usr/lib64 || true
          ls /usr/local/lib || true
          ls /lib || true
          ls /usr/lib || true
          ls /usr/x86_64-linux-gnu/lib64 || true
          ls /usr/x86_64-linux-gnu/lib || true
      #- name: Build and test Rust package
      #  uses: rcook/rust-package-action@v0.0.5
      #  with:
      #    target: ${{ matrix.target }}
