name: Release

env:
  tool_name: tuning-tool
  build_type: release

permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-musl
        include:
          - target: aarch64-apple-darwin
            target_ext: ""
            archive_type: .tar.gz
            build_os: macos-latest
          - target: x86_64-apple-darwin
            target_ext: ""
            archive_type: .tar.gz
            build_os: macos-13
          - target: x86_64-pc-windows-msvc
            target_ext: .exe
            archive_type: .zip
            build_os: windows-latest
          - target: x86_64-unknown-linux-musl
            target_ext: ""
            archive_type: .tar.gz
            build_os: ubuntu-latest
    runs-on: ${{ matrix.build_os }}
    steps:
      - name: Install dependencies
        if: matrix.host_os == 'ubuntu-latest'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libasound2-dev libjack-jackd2-dev
      - name: Build, test and release Rust tool
        uses: rcook/rust-tool-action@v0.0.34
        with:
          tool_name: ${{ env.tool_name }}
          target: ${{ matrix.target }}
          target_ext: ${{ matrix.target_ext }}
          archive_type: ${{ matrix.archive_type }}
          build_type: ${{ env.build_type }}
          code_sign: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_TOOL_ACTION_CODE_SIGN_CRT: ${{ secrets.RCOOK_CRT }}
          RUST_TOOL_ACTION_CODE_SIGN_CRTPASS: ${{ secrets.RCOOK_CRTPASS }}
